export default Object.freeze({
	SCHEDULE_UPDATED: 'SCHEDULE_UPDATED',
	OVERRIDE_STATE_CHANGED: 'OVERRIDE_STATE_CHANGED',
	MODE_CHANGED: 'MODE_CHANGED',
	REQUEST_DELETE: 'REQUEST_DELETE',
	CANCEL_DELETE: 'CANCEL_DELETE',
	CONFIRM_DELETE: 'CONFIRM_DELETE',
	REQUEST_EDIT: 'REQUEST_EDIT',
	SAVE_EDIT: 'SAVE_EDIT',
	CANCEL_EDIT: 'CANCEL_EDIT',
	STATUS_UPDATED: 'STATUS_UPDATED'
});
