language: node_js
node_js:
  - "8"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: cd aquanode-client && yarn && yarn ng -- build && cd ../aquanode-server && yarn && yarn start:dev
