language: node_js
node_js:
  - "8"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - wget abyz.co.uk/rpi/pigpio/pigpio.zip
  - unzip pigpio.zip
  - cd PIGPIO
  - make
  - sudo make install
before_script:
  - npm install -g typescript
script: cd $TRAVIS_BUILD_DIR/aquanode-client && yarn && yarn ng -- build && cd $TRAVIS_BUILD_DIR/aquanode-server && yarn && yarn build
